"""
Zephyrus-Reflective agent (glue-programming version).

Implements the core Zephyrus idea: LLM writes Python code, system executes it
against ZephyrusWorld tools, observes result, refines.

For Kaggle free tier, supports three backends:
- "no-llm" (deterministic): hardcoded pipeline, no GPU needed
- "vllm": vLLM-served Qwen2.5-Coder (T4 fits 7B-AWQ)
- "transformers": fallback when vLLM not available

The reflective loop:
  Q -> [LLM generates code] -> [execute] -> [observe] -> [LLM refines or finalizes]
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import textwrap
import time
import traceback
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# ----- Reflection log -----
@dataclass
class ReflectionStep:
    step_num: int
    role: str  # "code" | "exec" | "observation" | "final"
    content: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class AgentResult:
    question: str
    final_answer: str
    steps: list[ReflectionStep]
    artifacts: dict = field(default_factory=dict)


# ----- Code execution sandbox -----
def execute_python(code: str, workdir: Path, timeout_s: int = 60) -> tuple[str, str, int]:
    """Run Python code in subprocess. Returns (stdout, stderr, returncode)."""
    script_path = workdir / "_agent_step.py"
    script_path.write_text(code, encoding="utf-8")
    try:
        proc = subprocess.run(
            [sys.executable, "-u", str(script_path)],
            cwd=workdir,
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
        return proc.stdout, proc.stderr, proc.returncode
    except subprocess.TimeoutExpired:
        return "", f"Timeout after {timeout_s}s", -1
    except Exception as e:
        return "", f"Execution error: {e}", -1


# ----- LLM backend (optional, for the reflective loop) -----
class LLMBackend:
    """Abstract LLM backend. Subclass for vLLM/transformers/no-llm."""

    def generate(self, system: str, user: str, max_tokens: int = 2048) -> str:
        raise NotImplementedError


class NoLLMBackend(LLMBackend):
    """No-LLM mode: returns canned analysis. Used as baseline / Kaggle without GPU.

    The 'code' generated is a fixed analytical script that summarizes
    multi-model forecasts and ECMWF ensemble, produces a final answer.
    """

    def generate(self, system: str, user: str, max_tokens: int = 2048) -> str:
        # Hardcoded code that the system knows how to interpret the question
        # Wrap in ```python``` fences so the reflective loop regex picks it up
        return textwrap.dedent('''
            ```python
            # Generated by NoLLMBackend - structured analysis script
            import json
            import statistics
            from src.zephyrus_world.open_meteo import (
                get_forecast_multi_model, parse_forecast_bundle,
                get_ecmwf_ensemble, parse_ensemble_members,
                get_observation
            )

            # Use the question parameter if present
            q = qustion_text
            print(f"Question: {q}")
            print()

            # Step 1: Multi-model deterministic forecast
            raw = get_forecast_multi_model(LAT, LON, TARGET_DATE, TARGET_DATE)
            bundle = parse_forecast_bundle(raw, TARGET_DATE)
            print("=== Multi-model forecast ===")
            for m in bundle.models:
                if m.tmax_c is not None:
                    print(f"  {m.model:25s}: T_max={m.tmax_c:5.2f}°C  T_min={m.tmin_c}°C  rain={m.rain_mm}mm")

            # Step 2: ECMWF 50-member ensemble
            ens_raw = get_ecmwf_ensemble(LAT, LON, TARGET_DATE, TARGET_DATE)
            ens_parsed = parse_ensemble_members(ens_raw, TARGET_DATE)
            tmax_members = ens_parsed.get("members", {}).get("temperature_2m_max", [])
            if tmax_members:
                ens_mean = statistics.mean(tmax_members)
                ens_std = statistics.stdev(tmax_members)
                print(f"\\n=== ECMWF 50-member ensemble T_max ===")
                print(f"  mean={ens_mean:.2f}°C  std={ens_std:.2f}°C  range=[{min(tmax_members):.1f}, {max(tmax_members):.1f}]")
                p25, p50, p75 = sorted(tmax_members)[12], sorted(tmax_members)[25], sorted(tmax_members)[37]
                print(f"  IQR=[{p25:.1f}, {p75:.1f}]  median={p50:.1f}")

            # Step 3: Cross-model consensus
            det_tmax = [m.tmax_c for m in bundle.models if m.tmax_c is not None]
            print(f"\\n=== Cross-model consensus ===")
            if det_tmax:
                det_mean = statistics.mean(det_tmax)
                det_std = statistics.stdev(det_tmax) if len(det_tmax) > 1 else 0
                print(f"  Deterministic models: mean={det_mean:.2f}°C  std={det_std:.2f}°C")
            if tmax_members and det_tmax:
                # Hybrid: weight ensemble mean (50 members) with deterministic mean
                hybrid_mean = (ens_mean * 50 + det_mean * len(det_tmax)) / (50 + len(det_tmax))
                print(f"\\n=== Hybrid consensus (weighted: 50 ens + {len(det_tmax)} det) ===")
                print(f"  Hybrid mean T_max = {hybrid_mean:.2f}°C")
                # Save final numbers
                result = {
                    "ensemble_mean": ens_mean,
                    "ensemble_std": ens_std,
                    "deterministic_mean": det_mean,
                    "deterministic_std": det_std,
                    "hybrid_mean": hybrid_mean,
                    "n_deterministic": len(det_tmax),
                    "n_ensemble": len(tmax_members),
                }
                Path("/tmp/_agent_result.json").write_text(json.dumps(result, indent=2))
                print(f"\\n  -> Final consensus T_max: {hybrid_mean:.2f}°C")
            ```
        ''').replace("LAT", str(_LAT)).replace("LON", str(_LON)).replace("TARGET_DATE", f'"{_TARGET_DATE}"').replace("qustion_text", repr(_QUESTION))


# Globals set by NoLLMBackend on first use
_LAT = 0.0
_LON = 0.0
_TARGET_DATE = ""
_QUESTION = ""


def set_question_context(lat: float, lon: float, target_date: str, question: str):
    global _LAT, _LON, _TARGET_DATE, _QUESTION
    _LAT, _LON, _TARGET_DATE, _QUESTION = lat, lon, target_date, question


# ----- Reflective loop -----
def reflective_run(
    question: str,
    workdir: Path,
    lat: float,
    lon: float,
    target_date: str,
    backend: LLMBackend,
    max_iterations: int = 3,
    timeout_per_step: int = 60,
) -> AgentResult:
    """Run the Zephyrus-Reflective loop.

    1. Initialize question context (lat/lon/date)
    2. Backend generates code
    3. Execute code (ZephyrusWorld tools available)
    4. Observe stdout/stderr
    5. (Optional) Backend refines or finalizes
    6. Return AgentResult
    """
    set_question_context(lat, lon, target_date, question)
    workdir.mkdir(parents=True, exist_ok=True)

    # Make ZephyrusWorld importable in subprocess
    project_root = Path(__file__).parent.parent.parent.resolve()
    env = os.environ.copy()
    env["PYTHONPATH"] = str(project_root) + os.pathsep + env.get("PYTHONPATH", "")

    steps: list[ReflectionStep] = []
    final_answer = ""

    system_prompt = textwrap.dedent("""
        You are a Zephyrus-Reflective weather analysis agent. You have access to
        ZephyrusWorld tools (Python imports). Your task:

        1. Write Python code that uses the ZephyrusWorld tools to answer the question
        2. The system will execute the code and return stdout/stderr
        3. Analyze the result and either refine or finalize

        Available tools (import from src.zephyrus_world.open_meteo):
          - get_forecast_multi_model(lat, lon, start_date, end_date, models=None, ...)
          - get_ecmwf_ensemble(lat, lon, start_date, end_date, ...)
          - get_observation(lat, lon, start_date, end_date, ...)
          - geocode(name)
          - parse_forecast_bundle(raw, target_date)
          - parse_ensemble_members(raw, target_date)

        Variables available in scope: LAT, LON, TARGET_DATE, qustion_text.
        Output format: a single Python code block in ```python ... ``` fences.
    """).strip()

    user_prompt = f"Question: {question}\nLocation: lat={lat}, lon={lon}\nDate: {target_date}"

    for i in range(max_iterations):
        steps.append(ReflectionStep(step_num=i + 1, role="code",
                                    content=f"[Iteration {i+1}] generating code..."))
        raw = backend.generate(system_prompt, user_prompt)
        # Extract code block
        m = re.search(r"```python\s*(.*?)\s*```", raw, re.S)
        code = m.group(1) if m else raw
        steps.append(ReflectionStep(step_num=i + 1, role="code", content=code))

        # Execute
        env_script = textwrap.dedent(f"""
            import sys
            import json
            import statistics
            from pathlib import Path
            sys.path.insert(0, {str(project_root)!r})
            from src.zephyrus_world.open_meteo import (
                get_forecast_multi_model, parse_forecast_bundle,
                get_ecmwf_ensemble, parse_ensemble_members,
                get_observation, geocode
            )
        """)
        full_code = env_script + "\n" + code
        try:
            proc = subprocess.run(
                [sys.executable, "-u", "-c", full_code],
                cwd=workdir,
                capture_output=True,
                text=True,
                timeout=timeout_per_step,
                env=env,
            )
            stdout, stderr, rc = proc.stdout, proc.stderr, proc.returncode
        except subprocess.TimeoutExpired:
            stdout, stderr, rc = "", f"Timeout after {timeout_per_step}s", -1

        obs = f"STDOUT:\n{stdout}\nSTDERR:\n{stderr}\nRETURNCODE: {rc}"
        steps.append(ReflectionStep(step_num=i + 1, role="observation", content=obs))
        if rc != 0:
            user_prompt = f"{user_prompt}\n\nPrevious attempt failed. STDERR:\n{stderr}\n\nPlease fix the code."

    # Read final result if produced
    result_path = Path("/tmp/_agent_result.json")
    artifacts = {}
    if result_path.exists():
        artifacts = json.loads(result_path.read_text())
        final_answer = (
            f"Forecast consensus for {target_date} at ({lat}, {lon}): "
            f"T_max = {artifacts.get('hybrid_mean', 0):.2f}°C "
            f"(ensemble mean {artifacts.get('ensemble_mean', 0):.2f}°C ± "
            f"{artifacts.get('ensemble_std', 0):.2f}, "
            f"deterministic mean {artifacts.get('deterministic_mean', 0):.2f}°C ± "
            f"{artifacts.get('deterministic_std', 0):.2f}, "
            f"based on {artifacts.get('n_ensemble', 0)} ensemble + "
            f"{artifacts.get('n_deterministic', 0)} deterministic models)"
        )
    else:
        final_answer = f"Agent run completed. See {len(steps)} steps."

    return AgentResult(
        question=question,
        final_answer=final_answer,
        steps=steps,
        artifacts=artifacts,
    )


# ----- CLI -----
if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--lat", type=float, default=31.1433)
    p.add_argument("--lon", type=float, default=121.8052)
    p.add_argument("--date", type=str, default="2026-06-14")
    p.add_argument("--backend", type=str, default="no-llm",
                   choices=["no-llm", "vllm", "transformers"])
    p.add_argument("--workdir", type=str, default="/tmp/zephyrus_run")
    args = p.parse_args()

    backend = NoLLMBackend()  # extend with vLLM/transformers as needed
    result = reflective_run(
        question=f"What is the forecast T_max for {args.date} at lat={args.lat}, lon={args.lon}?",
        workdir=Path(args.workdir),
        lat=args.lat, lon=args.lon, target_date=args.date,
        backend=backend,
        max_iterations=1,
    )
    print()
    print("=" * 60)
    print("FINAL ANSWER:")
    print(result.final_answer)
    print()
    print("ARTIFACTS:", json.dumps(result.artifacts, indent=2))
